/**
 * TTS Service — immersive narration for The Chromatic Seal.
 *
 * Provider hierarchy (first available wins):
 *   1. ElevenLabs Streaming TTS  — eleven_multilingual_v2 + configured voice
 *      Credentials are read from environment variables VITE_ELEVENLABS_API_KEY and VITE_ELEVENLABS_VOICE_ID.
 *      Set these in your build environment or .env file.
 *
 *   2. Web Speech API fallback   — smart voice selection:
 *      Prefers deep British/US English male voices for fantasy feel.
 *
 * Usage:
 *   import { ttsService } from './ttsService.js'
 *   await ttsService.speak(text)
 *   ttsService.cancel()
 *
 * @module ttsService
 */

// Load credentials from src/config.js (gitignored, generated by CI or created locally).
// If the file is absent the service silently falls back to Web Speech API.
let ELEVENLABS_API_KEY = ''
try {
  const cfg = await import('../config.js')
  ELEVENLABS_API_KEY = cfg.ELEVENLABS_API_KEY ?? ''
} catch { /* config.js not present — Web Speech API will handle narration */ }

// ─── ElevenLabs config ───────────────────────────────────────────────────────

const ELEVENLABS_MODEL = 'eleven_multilingual_v2'

// Curated DnD narrator voices — one is randomly chosen per session/playthrough.
// A page reload picks a fresh narrator.
const DND_NARRATOR_VOICES = [
  'oR4uRy4fHDUGGISL0Rev',  // primary voice (user's pick)
  'pNInz6obpgDQGcFmaJgB',  // Adam    — dominant, deep male
  'nPczCjzI2devNBz1zQrb',  // Brian   — deep, resonant storyteller
  'JBFqnCBsd6RMkjVDRZzb',  // Bill    — authoritative narrator
  'nJvj5shg2xu1GKGxqfkE',  // Yusuf   — smooth, professional narrator
  'N2lVS1w4EtoT3dr4eOWO',  // Callum  — intense, dramatic
]

const ELEVENLABS_VOICE_ID =
  DND_NARRATOR_VOICES[Math.floor(Math.random() * DND_NARRATOR_VOICES.length)]

const ELEVENLABS_VOICE_SETTINGS = {
  stability:        0.65,   // higher stability for long narration passages
  similarity_boost: 0.80,
  style:            0.35,   // slight expressiveness for dramatic moments
  use_speaker_boost: true,
}

// ─── Web Speech voice selection ──────────────────────────────────────────────

/**
 * Ranked list of preferred Web Speech voice name substrings.
 * Checked in order — first match wins.
 * Preference: deep British male > US male > any English.
 */
const WSA_VOICE_PREFS = [
  'george', 'daniel', 'arthur',        // UK English males
  'microsoft david', 'microsoft mark', // Windows deep males
  'alex',                              // macOS classic deep voice
  'google uk english male',
  'fred',                              // macOS older deep voice
  'en-gb', 'en_gb',                    // any UK English
  'en-us', 'en_us',                    // fallback US English
]

function pickBestVoice(voices) {
  const lower = voices.map(v => ({ v, key: v.name.toLowerCase() }))
  for (const pref of WSA_VOICE_PREFS) {
    const match = lower.find(({ key }) => key.includes(pref))
    if (match) return match.v
  }
  return voices.find(v => v.lang.startsWith('en')) ?? voices[0] ?? null
}

// ─── Service class ────────────────────────────────────────────────────────────

class TTSService {
  constructor() {
    /** @type {HTMLAudioElement|null} */
    this._audio       = null
    /** @type {SpeechSynthesisUtterance|null} */
    this._utterance   = null
    this._speaking    = false
    this._listeners   = new Set()
  }

  get speaking() { return this._speaking }

  /** @param {Function} fn – called with ('start'|'end'|'error') */
  onStateChange(fn) { this._listeners.add(fn); return () => this._listeners.delete(fn) }

  _emit(event) { this._listeners.forEach(fn => fn(event)) }

  _setState(speaking) { this._speaking = speaking; this._emit(speaking ? 'start' : 'end') }

  // ── ElevenLabs ─────────────────────────────────────────────────────────────

  async _speakElevenLabs(text) {
    if (!ELEVENLABS_API_KEY) return false

    try {
      const res = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${ELEVENLABS_VOICE_ID}/stream`,
        {
          method: 'POST',
          headers: {
            'xi-api-key':   ELEVENLABS_API_KEY,
            'Content-Type': 'application/json',
            'Accept':       'audio/mpeg',
          },
          body: JSON.stringify({
            text,
            model_id:       ELEVENLABS_MODEL,
            voice_settings: ELEVENLABS_VOICE_SETTINGS,
          }),
        }
      )

      if (!res.ok) {
        console.warn(`[TTS] ElevenLabs ${res.status} — falling back to Web Speech API`)
        return false
      }

      const blob = await res.blob()
      const url  = URL.createObjectURL(blob)

      this._audio = new Audio(url)
      this._audio.onended = () => {
        URL.revokeObjectURL(url)
        this._audio = null
        this._setState(false)
      }
      this._audio.onerror = () => {
        URL.revokeObjectURL(url)
        this._audio = null
        this._setState(false)
        this._emit('error')
      }

      this._setState(true)
      await this._audio.play()
      return true

    } catch (err) {
      console.warn('[TTS] ElevenLabs fetch failed:', err.message)
      return false
    }
  }

  // ── Web Speech API ─────────────────────────────────────────────────────────

  _speakWSA(text) {
    if (!('speechSynthesis' in window)) return false

    const voices = window.speechSynthesis.getVoices()
    const voice  = voices.length ? pickBestVoice(voices) : null

    const utt    = new SpeechSynthesisUtterance(text)
    utt.lang     = 'en-GB'
    utt.rate     = 0.86
    utt.pitch    = voice ? 0.9 : 1.0
    if (voice) utt.voice = voice

    utt.onstart = () => this._setState(true)
    utt.onend   = () => { this._utterance = null; this._setState(false) }
    utt.onerror = () => { this._utterance = null; this._setState(false); this._emit('error') }

    this._utterance = utt
    window.speechSynthesis.speak(utt)
    return true
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Speak `text` using the best available provider.
   * @param {string} text
   */
  async speak(text) {
    if (!text?.trim()) return
    this.cancel()

    const usedEL = await this._speakElevenLabs(text)
    if (!usedEL) this._speakWSA(text)
  }

  /** Stop any current speech immediately. */
  cancel() {
    if (this._audio) {
      this._audio.pause()
      this._audio.currentTime = 0
      this._audio = null
    }
    if (typeof window !== 'undefined' && window.speechSynthesis?.speaking) {
      window.speechSynthesis.cancel()
    }
    this._utterance = null
    if (this._speaking) this._setState(false)
  }
}

/** Singleton instance shared across the app */
export const ttsService = new TTSService()
